colorscheme palenight

# Relative line numbers
add-highlighter global/ number-lines -relative -separator " " -hlcursor

# UI settings
# TODO: turn off once familiar with stuff
set-option global ui_options terminal_assistant=none
set-option global startup_info_version 99999999999999 # Don't show changelog
set-option global scrolloff 8,8

# Enable LSP
# This has to be after general highlighters so that line numbers appear closest to the buffer contents
# lsp-enable

# Auto-reload buffers on external change
set-option global autoreload yes

# Ripgrep instead of grep
set-option global grepcmd "rg -Hn --no-heading --sort path --vimgrep"

# def -params 1 extend-line-down %{
#   exec "<a-:>%arg{1}x"
# }
# def -params 1 extend-line-up %{
#   exec "<a-:><a-;>%arg{1}K<a-;>"
#   try %{
#     exec -draft ';<a-K>\n<ret>'
#     exec X
#   }
#   exec '<a-;><a-X>'
# }
# map global normal x ':extend-line-down %val{count}<ret>'
# map global normal X ':extend-line-up %val{count}<ret>'

# -----------------------
# ----- Keybindings -----
# -----------------------

# Centered jumps
map global normal <c-o> <c-o>vv
map global normal <c-i> <c-i>vv

# Comment selection
map global normal "#" ":comment-line<ret>"

# ----- Big TODO List -----
# TODO, WARN, NOTE Plugin replacement
# vim-gitgutter -> inbuilt git commant git show-diff
